### ISSUE TITLE
Aliasing config_scopes in local scope

### ISSUE THREAD

**Issue by sjmc7** [fr33jc/bang#3]
It'd be useful to be able to rename a global config in the local scope. This would allow multiple server roles to share a local config_scope without copy and pasting; a mixture of reusing globally defined config sections with the flexibility of local config_scopes.

For example:

```
- name: logging_servers
  # Inside a server role definition:
  config_scopes:
      # Could put 'elasticsearch' here but would need to copy
      # it for each role that requires it
      - ....
  config_aliases:
      # Playbook can refer to {{elasticsearch.something}}
      - elasticsearch: elasticsearch_logging

- name: monitoring
  config_aliases:
      - elasticsearch: elasticsearch_logging

# Global scope
elasticsearch_logging:
    cluster_name: logging

# Second set of elasticsearch config options
elasticsearch_documents:
    cluster_name: documents
```
